### ISSUE TITLE
setOptions not available

### ISSUE THREAD

**Issue by dd10-e** [pqina/svelte-filepond#12]
Hello Rik !

It seems that we can't `setOptions` use this way : 
```js
import FilePond, { registerPlugin, setOptions } from 'svelte-filepond';
import es_ES from 'filepond/locale/es-es.js';
// ...

setOptions(es_ES)
```

It seems to be a missing feature from the original `Filepond` library. Should it be done this way ?

**Comment by rikschennink** [comment]
It's indeed not exported, with the framework you should use the component to interact with FilePond. I'd just spread the props on the component instead.
