### ISSUE TITLE
Sapper integration

### ISSUE THREAD

**Issue by myangga** [pqina/svelte-filepond#2]
Hi, having some issues with Filepond integration to Sapper (Svelte JS framework).

First because following the install steps leads to 500 error because of non SSR component.
So I added Filepond and svelte-filepond packages as dev dependencies:
```
npm install -D svelte-filepond filepond
```
Then all seems to work execpt that I don't succeed to get the file serverId... Still get undefined (returning all page HTML).
I did create a Git repo to test and reproduce here: https://github.com/myangga/sapper-filepond

Thanks for support.

**Comment by myangga** [comment]
BTW, forgot to add "express-fileupload" to be able to load/process file on server, and added reference inside server.js. Now you can see uploaded file in /tmp/ folder of host platform (setup in server.js). But still the serverid is not returned.

**Comment by rikschennink** [comment]
Hi, I don't have any experience with Sapper or express-fileupload. What I can tell you is that FilePond pushes posts a formdata object that contains both a file metadata string and a file blob (see: https://pqina.nl/filepond/docs/patterns/api/server/#introduction). 

Make sure the server end point returns a plain text response with a unique file id.

**Comment by myangga** [comment]
I succeeded to use it finally, by grabing the tempFilePath via the req parameter in upload async process I created, and forwarding the file name as serverid. Thanks
