### ISSUE TITLE
Fix missing exports condition

### ISSUE THREAD

**Issue by NitrusAphalion** [pqina/svelte-filepond#22]
There is nothing special about this, just needs update for sveltekit 2.
Can follow instructions in https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

It comes out in terminal after 'yarn dev' as:
```
10:14:29 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-filepond@0.2.0
Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

From package.json:
        "@sveltejs/vite-plugin-svelte": "^3.0.0",

**Comment by rikschennink** [comment]
Then please submit a PR?
